css-three-column-layout - Matt Cha
matt-cha/c1222-code-solutions pull request #18
Opened 2022-12-09 00:30 UTC by matt-cha

![Screen Shot 2022-12-08 at 4 29 47 PM](https://user-images.githubusercontent.com/113474295/206595273-0899b2c7-2fe7-4c7d-820a-1ebefba81e87.png)

2022-12-12 23:38 UTC, codingcodymiller requested changes

2022-12-12 23:38 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  margin-right: 25px;
`column` classes should only have `flex-basis` applied, nothing else.

2022-12-13 18:28 UTC, matt-cha commented on css-three-column-layout/styles.css
> +  margin-right: 25px;
![Screen Shot 2022-12-13 at 10 26 26 AM](https://user-images.githubusercontent.com/113474295/207415431-41d4bc8b-f3b6-45db-afc4-1f3da98ea02c.png)
thanks cody, adjusted column class to only have flex-basis!

2022-12-13 18:43 UTC, codingcodymiller requested changes

2022-12-13 18:43 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +}
This shouldn't be necessary. You only need either `flex-basis` or `width`, not both. Since we are working within a layout class system designed around flexbox, `flex-basis` is preferable

2022-12-13 18:53 UTC, matt-cha commented on css-three-column-layout/styles.css
> +}
<img width="1129" alt="Screen Shot 2022-12-13 at 10 51 29 AM" src="https://user-images.githubusercontent.com/113474295/207419902-f3750d56-38d6-4083-b977-12437be473b8.png">
Renamed the classes to not include column-one-third thanks cody!

2022-12-16 20:05 UTC, codingcodymiller requested changes

2022-12-16 20:05 UTC, codingcodymiller commented on css-three-column-layout/styles.css
> +  flex-basis: 100%;
This needs an accurate measurement of `33%`

2022-12-17 18:38 UTC, matt-cha commented on css-three-column-layout/styles.css
> +  flex-basis: 100%;
![Screen Shot 2022-12-17 at 10 37 43 AM](https://user-images.githubusercontent.com/113474295/208256572-9877869f-b121-4054-af32-78766e8aa69d.png)
adjusted this thanks cody!

2022-12-19 17:37 UTC, codingcodymiller approved these changes

2022-12-19 18:28 UTC, merged