css-positioning - Matt Cha
matt-cha/c1222-code-solutions pull request #19
Opened 2022-12-09 16:45 UTC by matt-cha

https://user-images.githubusercontent.com/113474295/206750706-200316d3-9418-4ea9-8f0f-69e66ef060e1.mp4

![Screen Shot 2022-12-08 at 6 35 51 PM](https://user-images.githubusercontent.com/113474295/206750717-25de023a-f44c-4154-8206-51683dce4d34.png)
<img width="444" alt="Screen Shot 2022-12-08 at 5 41 50 PM" src="https://user-images.githubusercontent.com/113474295/206750719-752e5f9b-b4ac-48eb-8bde-538b93baf03f.png">

2022-12-09 18:34 UTC, codingcodymiller requested changes

2022-12-09 18:34 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  left: 230px;
**_WOAH_**, this is a big measurement. You should try using the the opposite side, you can use a much smaller unit if you do that.

2022-12-09 18:34 UTC, codingcodymiller commented on css-positioning/absolute.css
> +  top: 160px;
**_WOAH_**, this is a big measurement. You should try using the the opposite side, you can use a much smaller unit if you do that.

2022-12-09 19:41 UTC, matt-cha commented on css-positioning/absolute.css
> +  top: 160px;
<img width="963" alt="Screen Shot 2022-12-09 at 11 40 26 AM" src="https://user-images.githubusercontent.com/113474295/206783823-781ab8ea-7286-400c-bf43-4c77c0128a2f.png">
Fixed the absolute unit sizing thank you!

2022-12-12 17:40 UTC, codingcodymiller approved these changes

2022-12-12 19:27 UTC, merged