css-two-column-layout - Matt Cha
matt-cha/c1222-code-solutions pull request #20
Opened 2022-12-09 19:38 UTC by matt-cha

<img width="823" alt="Screen Shot 2022-12-09 at 11 34 35 AM" src="https://user-images.githubusercontent.com/113474295/206783444-310430cc-d665-4676-bed3-21a4f2e645e3.png">

2022-12-13 00:02 UTC, codingcodymiller requested changes

2022-12-13 00:02 UTC, codingcodymiller commented on css-two-column-layout/styles.css
> +}
`column` classes should only ever have `flex-basis`, nothing else. Anything additional necessary should be on a separate class.

2022-12-13 21:52 UTC, matt-cha commented on css-two-column-layout/styles.css
> +}
<img width="1171" alt="Screen Shot 2022-12-13 at 1 50 49 PM" src="https://user-images.githubusercontent.com/113474295/207451645-8640535f-7982-4bd3-aeb2-7dc98a816143.png">

2022-12-16 20:06 UTC, codingcodymiller approved these changes
Much better!

2022-12-19 18:29 UTC, merged