javascript-loops-practice
matt-cha/c1222-code-solutions pull request #34
Opened 2022-12-16 00:43 UTC by matt-cha

<img width="492" alt="Screen Shot 2022-12-15 at 4 41 31 PM" src="https://user-images.githubusercontent.com/113474295/207996263-d958e04b-00bb-4cee-ad28-e3633a4b1c03.png">

2022-12-16 23:26 UTC, codingcodymiller requested changes

2022-12-16 23:26 UTC, codingcodymiller commented on javascript-loops-practice/add-suffix-to-all.js
> +    newArray[i] += suffix;
This is changing the original array, which is really bad news 🤮

2022-12-17 18:53 UTC, matt-cha commented on javascript-loops-practice/add-suffix-to-all.js
> +    newArray[i] += suffix;
Fixed the function to not adjust the original array thanks cody!

2022-12-19 17:50 UTC, codingcodymiller approved these changes

2022-12-19 18:27 UTC, merged