Object manipulation 2
matt-cha/c1222-code-solutions pull request #57
Opened 2022-12-28 04:27 UTC by matt-cha

![Screen Shot 2022-12-27 at 8 21 34 PM](https://user-images.githubusercontent.com/113474295/209757327-2904c08a-5818-412e-b9de-fa1ebf6ad2ca.png)

2023-01-20 21:54 UTC, codingcodymiller requested changes

2023-01-20 21:54 UTC, codingcodymiller commented on object-manipulation-2/src/invert.js
> +  newValues = Object.values(source);
Try to do this without turning the object into an array 🤓

2023-01-20 21:54 UTC, codingcodymiller commented on object-manipulation-2/src/omit.js
> +  var sourceKeys = Object.keys(source);
Try to do this without turning the object into an array 🤓

2023-01-24 23:38 UTC, RobertGardner requested changes
Not a bad start, but more work is needed on some of the exercises.

2023-01-24 23:38 UTC, RobertGardner commented on array-manipulation-2/src/chunk.js
> +  var newArray = array.split('', 0, size);
`split` is a method on String, not on Array. I'm not sure what you are trying to do here, so I can't help!

2023-01-24 23:38 UTC, RobertGardner commented on array-manipulation-2/src/chunk.js
> +/* need to use slice? */
This code using slice is a good start. You probably need to loop, slicing out a chunk array each time.

Another way to approach this (which doesn't use slice) is to loop through the array and push each element into a `chunk` array. After pushing the `size`th element into `chunk`, push that chunk into the `chunks` array (`newArray` in your code) and start a new `chunk` array.

2023-01-25 02:46 UTC, matt-cha commented on array-manipulation-2/src/chunk.js
> +/* need to use slice? */
This is a bit of a mess but these fixes are for array-manipulation-2 and this exercise should be object-manipulation-2! 

I accidentally saved these changes when doing the exercises simultaneously on the wrong branch so I had chunk.js finished under array-manipulation-2 exercise. But I did fix the other problems above that you commented on + copied my code for chunk.js. 

Sorry for the confusion Robert! If you want to check again for these commented solutions even though it is for a different exercise that'd be great thanks!

2023-02-21 18:02 UTC, merged