javascript-carousel
matt-cha/c1222-code-solutions pull request #66
Opened 2023-01-05 02:11 UTC by matt-cha

https://user-images.githubusercontent.com/113474295/210685838-f7c292f5-225a-4c56-83e2-8c54a17883a5.mp4

2023-01-20 22:11 UTC, codingcodymiller requested changes
This is VERY manual. If you ever needed to add another slide, you would have to write a bunch of new code and revise everything. You should find a way to do this that won't need to be changed and updated if the number of slides ever changes.

2023-01-23 23:48 UTC, RobertGardner approved these changes
Nice!

I made some optional comments on how you might improve your code. They are optional and intended to get you thinking about these things as you write code. Feel free to ignore them if you're slammed with other things!

2023-01-23 23:48 UTC, RobertGardner commented on javascript-carousel/main.js
> +var count = 0;
`count` as a variable usually implies that it is keeping track of how many. It looks, though, like you are using it to keep track of the current image. Maybe the name `current` would be better?

2023-01-23 23:48 UTC, RobertGardner commented on javascript-carousel/main.js
> +    count = dotNumber[4];
If I understand correctly, this code is relying on dotNumber being a string that looks like `dot-N` (where N is the count). This mostly works. There are a few minor gotchas here. (Note that in React this will be much easier and you won't have to use the class name trick. So don't worry too much about making these changes.)

First, you are assuming that `dot-N` is the first class name in 'class'. It will be because you built it that way, but it's easy to forget that and add another class at the front, which will break your code. The best way to do this would be to scan the string for `dot-` and then use that to figure out the index.

Second, you are just grabbing one character out of the class name string. If you have more than 9 images in your carousel, this won't work. The best way to do this would be to take all the characters up to the space (or end of the string if there are no spaces).

Finally, when you use `dotNumber[4]` it is returning a string. But you are using `count` as a number. There are places in your code where this could cause a crash. You need to convert `dotNumber[4]` to a number. (Have you learned how to do that? The best way is probably to call `parseInt(dotNumber[4])`.)

2023-01-23 23:48 UTC, RobertGardner commented on javascript-carousel/main.js
> +    intervalId = null;
This line is not necessary since you are reassigning `intervalId` in the next line.

2023-01-23 23:48 UTC, RobertGardner commented on javascript-carousel/main.js
> +  intervalId = setInterval(changeImageThreeSec, 3000);
Since you are using 3000 several times, it would be good to define a variable for it at the top of the file. Then if you want to change from 3 seconds to something else you only have to change one place.

2023-01-25 02:15 UTC, matt-cha commented on javascript-carousel/main.js
> +    count = dotNumber[4];
Thank you for the feedback Robert! These are good points to keep in mind definitely

2023-02-04 02:37 UTC, merged